services:
  frontend:
    build:
      context: ./asl-tutor
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./asl-tutor/src
          target: /usr/src/app/src
        - action: rebuild
          path: ./asl-tutor/package.json
          target: /usr/src/app/package.json
    ports:
      - "4200:4200"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    develop:
      watch:
        # - action: sync+restart
        #   path: ./backend
        #   target: /app
        - action: rebuild
          path: ./backend/requirements.txt
    ports:
      - "8080:8080"